package componentmetrics

// BackendRoutes freezes the complete production router, including health/readiness.
func BackendRoutes() []Route {
	return []Route{
		{Method: "GET", Template: "/api/v1/alerts/catalog"},
		{Method: "GET", Template: "/api/v1/alerts/rules"},
		{Method: "POST", Template: "/api/v1/alerts/rules"},
		{Method: "GET", Template: "/api/v1/alerts/rules/:ruleId"},
		{Method: "PUT", Template: "/api/v1/alerts/rules/:ruleId"},
		{Method: "DELETE", Template: "/api/v1/alerts/rules/:ruleId"},
		{Method: "POST", Template: "/api/v1/alerts/rules/:ruleId/enable"},
		{Method: "POST", Template: "/api/v1/alerts/rules/:ruleId/disable"},
		{Method: "GET", Template: "/api/v1/alerts/current"},
		{Method: "GET", Template: "/api/v1/alerts/history"},

		{Method: "GET", Template: "/api/v1/admin/users/:userId"},
		{Method: "PUT", Template: "/api/v1/admin/users/:userId/role"},
		{Method: "GET", Template: "/api/v1/admin/audit-events"},
		{Method: "GET", Template: "/health"},
		{Method: "GET", Template: "/ready"},
		{Method: "POST", Template: "/api/v1/auth/register"},
		{Method: "POST", Template: "/api/v1/auth/login"},
		{Method: "POST", Template: "/api/v1/auth/logout"},
		{Method: "GET", Template: "/api/v1/users/me"},
		{Method: "PATCH", Template: "/api/v1/users/me/profile"},
		{Method: "PUT", Template: "/api/v1/users/:userId/follow"},
		{Method: "DELETE", Template: "/api/v1/users/:userId/follow"},
		{Method: "GET", Template: "/api/v1/users/me/following"},
		{Method: "GET", Template: "/api/v1/users/me/followers"},
		{Method: "GET", Template: "/api/v1/posts/following"},
		{Method: "GET", Template: "/api/v1/users/:username"},
		{Method: "GET", Template: "/api/v1/users/:username/posts"},
		{Method: "GET", Template: "/api/v1/search/users"},
		{Method: "POST", Template: "/api/v1/posts"},
		{Method: "GET", Template: "/api/v1/posts"},
		{Method: "GET", Template: "/api/v1/bookmarks"},
		{Method: "GET", Template: "/api/v1/posts/:postId"},
		{Method: "PATCH", Template: "/api/v1/posts/:postId"},
		{Method: "DELETE", Template: "/api/v1/posts/:postId"},
		{Method: "POST", Template: "/api/v1/posts/:postId/comments"},
		{Method: "GET", Template: "/api/v1/posts/:postId/comments"},
		{Method: "PUT", Template: "/api/v1/posts/:postId/bookmark"},
		{Method: "DELETE", Template: "/api/v1/posts/:postId/bookmark"},
		{Method: "PUT", Template: "/api/v1/posts/:postId/like"},
		{Method: "DELETE", Template: "/api/v1/posts/:postId/like"},
		{Method: "GET", Template: "/api/v1/search/posts"},
		{Method: "GET", Template: "/api/v1/notifications"},
		{Method: "PATCH", Template: "/api/v1/notifications/:notificationId/read"},
		{Method: "GET", Template: "/api/v1/observability/metrics"},
		{Method: "GET", Template: "/api/v1/observability/metrics/catalog"},
		{Method: "GET", Template: "/api/v1/observability/logs"},
		{Method: "GET", Template: "/api/v1/observability/events"},
		{Method: "GET", Template: "/api/v1/exporter-plugins"},
		{Method: "GET", Template: "/api/v1/exporter-plugins/catalog"},
		{Method: "POST", Template: "/api/v1/exporter-plugins/:pluginId/connection-test"},
		{Method: "POST", Template: "/api/v1/exporter-plugins/:pluginId/install"},
		{Method: "PUT", Template: "/api/v1/exporter-plugins/:pluginId/configuration"},
		{Method: "GET", Template: "/api/v1/exporter-plugins/:pluginId"},
		{Method: "POST", Template: "/api/v1/exporter-plugins/install"},
		{Method: "POST", Template: "/api/v1/exporter-plugins/:pluginId/start"},
		{Method: "POST", Template: "/api/v1/exporter-plugins/:pluginId/stop"},
		{Method: "POST", Template: "/api/v1/exporter-plugins/:pluginId/update"},
	}
}
