CREATE TABLE IF NOT EXISTS alert_rules (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(80) COLLATE utf8mb4_bin NOT NULL,
 enabled BOOLEAN NOT NULL,
 severity ENUM('warning','critical') NOT NULL,
 source ENUM('metrics','logs','events') NOT NULL,
 selector JSON NOT NULL,
 reducer VARCHAR(16) NOT NULL,
 operator VARCHAR(8) NOT NULL,
 threshold DOUBLE NOT NULL,
 window_seconds INT NOT NULL,
 for_seconds INT NOT NULL,
 revision BIGINT UNSIGNED NOT NULL,
 created_by BIGINT UNSIGNED NOT NULL,
 updated_by BIGINT UNSIGNED NOT NULL,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 deleted_at DATETIME(6) NULL,
 live_name VARCHAR(80) COLLATE utf8mb4_bin GENERATED ALWAYS AS (IF(deleted_at IS NULL,name,NULL)) STORED,
 UNIQUE KEY uq_alert_name(live_name),
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT,
 FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS alert_incidents (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 rule_id BIGINT UNSIGNED NOT NULL,
 revision BIGINT UNSIGNED NOT NULL,
 name VARCHAR(80) NOT NULL,
 severity ENUM('warning','critical') NOT NULL,
 source ENUM('metrics','logs','events') NOT NULL,
 object JSON NOT NULL,
 status ENUM('firing','recovered','closed') NOT NULL,
 first_triggered_at DATETIME(6) NOT NULL,
 last_triggered_at DATETIME(6) NOT NULL,
 last_evaluated_at DATETIME(6) NOT NULL,
 recovered_at DATETIME(6) NULL,
 closed_at DATETIME(6) NULL,
 resolution_reason VARCHAR(32) NOT NULL DEFAULT '',
 observed_value DOUBLE NULL,
 evaluation_count BIGINT UNSIGNED NOT NULL,
 active_rule_id BIGINT UNSIGNED GENERATED ALWAYS AS (IF(status='firing',rule_id,NULL)) STORED,
 UNIQUE KEY uq_active_rule(active_rule_id),
 INDEX idx_current(status,severity,first_triggered_at,id),
 INDEX idx_history(first_triggered_at,id),
 FOREIGN KEY(rule_id) REFERENCES alert_rules(id) ON DELETE RESTRICT
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS alert_rule_states (
 rule_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
 state ENUM('disabled','normal','pending','firing') NOT NULL,
 data_status ENUM('unknown','ok','stale') NOT NULL DEFAULT 'unknown',
 pending_since DATETIME(6) NULL,
 active_incident_id BIGINT UNSIGNED NULL UNIQUE,
 observed_value DOUBLE NULL,
 last_evaluated_at DATETIME(6) NULL,
 last_success_at DATETIME(6) NULL,
 error_code VARCHAR(32) NOT NULL DEFAULT '',
 lease_owner CHAR(32) NOT NULL DEFAULT '',
 lease_until DATETIME(6) NULL,
 next_evaluation_at DATETIME(6) NOT NULL,
 INDEX idx_claim(next_evaluation_at,lease_until,rule_id),
 FOREIGN KEY(rule_id) REFERENCES alert_rules(id) ON DELETE RESTRICT,
 FOREIGN KEY(active_incident_id) REFERENCES alert_incidents(id) ON DELETE RESTRICT
) ENGINE=InnoDB;
