<script setup lang="ts">
import AdminIcon from "../components/AdminIcon.vue"
import AdminStat from "../components/AdminStat.vue"
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import { ApiError, requestValidatedData, requestValidatedPage, requestVoid } from '../services/http'
import { isCatalog, isRule, isIncident, type Catalog, type Rule, type Incident } from '../services/management'
type Input={name:string;source:string;severity:string;selector:{metric:string;labels:Record<string,string>};reducer:string;operator:string;threshold:number;window:string;for:string;enabled?:boolean;revision?:number}
const catalog=ref<Catalog|null>(null),rules=ref<Rule[]>([]),incidents=ref<Incident[]>([]),tab=ref('current'),busy=ref(false),message=ref(''),next=ref<string|null>(null),editing=ref<Rule|null>(null),showForm=ref(false)
const selectedId=ref<number|null>(null),detail=ref<HTMLElement|null>(null),severityFilter=ref(''),statusFilter=ref(''),search=ref(''),loaded=ref(false)
const selectedIncident=computed(()=>incidents.value.find(row=>row.id===selectedId.value))
const visibleIncidents=computed(()=>incidents.value.filter(row=>(!severityFilter.value||row.severity===severityFilter.value)&&(!statusFilter.value||row.status===statusFilter.value)&&(!search.value||row.name.includes(search.value))))
let selectionButton:HTMLElement|null=null
async function selectIncident(id:number,event:Event){selectionButton=event.currentTarget as HTMLElement;selectedId.value=id;await nextTick();detail.value?.focus()}
function closeDetail(){selectedId.value=null;selectionButton?.focus()}
watch([severityFilter,statusFilter,search],()=>{selectedId.value=null})
const source=ref('metrics'),metric=ref(''),tuple=ref(0),name=ref(''),severity=ref('warning'),reducer=ref('last'),operator=ref('gt'),threshold=ref(0),windowSize=ref('1m'),forSize=ref('0s')
const definition=computed(()=>catalog.value?.metrics.find(m=>m.metric===metric.value))
const selectors=computed<Record<string,string>[]>(()=>{if(!catalog.value)return [];if(source.value==='metrics'){const d=definition.value;return d?d.allowed_tuples.map(t=>Object.fromEntries(d.label_keys.map((k,i)=>[k,t[i]!]))):[]}const c=source.value==='logs'?catalog.value.logs:catalog.value.events;return c.allowed_combinations.length?c.allowed_combinations:Object.entries(c.fields).flatMap(([k,vs])=>vs.map(v=>({[k]:v})))})
const reducers=computed(()=>source.value==='metrics'?definition.value?.reducers??[]:['count'])
const durations=computed(()=>catalog.value?.for.filter(v=>v==='0s'||v==='1m'||windowSize.value!=='1m')??[])
watch(source,()=>{tuple.value=0;reducer.value=source.value==='metrics'?'last':'count'})
watch(metric,()=>{tuple.value=0;reducer.value=definition.value?.reducers[0]??'last'})
watch(windowSize,()=>{if(!durations.value.some(v=>v===forSize.value))forSize.value='0s'})
async function load(more=false){if(busy.value)return;busy.value=true;message.value='';if(!more)selectedId.value=null;try{if(!catalog.value){catalog.value=await requestValidatedData('/alerts/catalog',isCatalog);metric.value=catalog.value.metrics[0]?.metric??''}const page=await requestValidatedPage<Rule|Incident>('/alerts/'+tab.value+(more&&next.value?'?cursor='+encodeURIComponent(next.value):''),tab.value==='rules'?isRule:isIncident);if(tab.value==='rules')rules.value=more?[...rules.value,...page.data as Rule[]]:page.data as Rule[];else incidents.value=more?[...incidents.value,...page.data as Incident[]]:page.data as Incident[];next.value=page.nextCursor;loaded.value=true;if(!more&&tab.value!=='rules'&&window.innerWidth>1000)selectedId.value=incidents.value[0]?.id??null}catch{message.value='告警读取失败'}finally{busy.value=false}}
async function selectTab(value:string){tab.value=value;loaded.value=false;selectedId.value=null;next.value=null;incidents.value=[];await load()}
function create(){editing.value=null;name.value='';showForm.value=true}
async function edit(r:Rule){editing.value=r;source.value=r.source;metric.value=r.selector.metric;await nextTick();tuple.value=Math.max(0,selectors.value.findIndex(s=>JSON.stringify(Object.entries(s).sort())===JSON.stringify(Object.entries(r.selector.labels).sort())));name.value=r.name;severity.value=r.severity;reducer.value=r.reducer;operator.value=r.operator;threshold.value=r.threshold;windowSize.value=r.window;forSize.value=r.for;showForm.value=true}
async function failed(e:unknown){busy.value=false;if(e instanceof ApiError&&e.status===409){showForm.value=false;await load();message.value='已被其他管理员修改，请重新读取后操作。'}else message.value='操作失败，请检查规则或稍后重试。'}
async function save(){if(busy.value||!selectors.value[tuple.value])return;if(editing.value&&!window.confirm('更新会关闭当前 firing 告警并重置评估状态，确认更新？'))return;busy.value=true;try{const body:Input={name:name.value,source:source.value,severity:severity.value,selector:{metric:source.value==='metrics'?metric.value:'',labels:selectors.value[tuple.value]!},reducer:reducer.value,operator:operator.value,threshold:threshold.value,window:windowSize.value,for:forSize.value};if(editing.value)body.revision=editing.value.revision;else body.enabled=true;await requestValidatedData('/alerts/rules'+(editing.value?'/'+editing.value.id:''),isRule,{method:editing.value?'PUT':'POST',body:JSON.stringify(body)});showForm.value=false;busy.value=false;await load();message.value='规则已保存'}catch(e){await failed(e)}finally{busy.value=false}}
async function mutate(r:Rule,action:string){if(busy.value)return;if(action!=='enable'&&!window.confirm('此操作会关闭当前 firing 告警，确认'+action+'？'))return;busy.value=true;try{const init={method:action==='delete'?'DELETE':'POST',body:JSON.stringify({revision:r.revision})};const path='/alerts/rules/'+r.id+(action==='delete'?'':'/'+action);if(action==='delete')await requestVoid(path,init);else await requestValidatedData(path,isRule,init);busy.value=false;await load();message.value='操作成功'}catch(e){await failed(e)}finally{busy.value=false}}
onMounted(()=>load())
</script>
<template><section class="alerts-page"><div class="admin-title"><div><h2>Alerts</h2><p>告警监控与事件处理，及时发现并处理系统异常。</p></div><button class="icon-button" aria-label="刷新告警" :disabled="busy" @click="load()"><AdminIcon name="refresh" /></button></div><p v-if="message" class="notice" role="status">{{message}}</p><template v-if="tab==='rules'"><nav class="alert-tabs" aria-label="告警视图"><button v-for="t in ['current','history','rules']" :key="t" :disabled="busy" :aria-pressed="tab===t" @click="selectTab(t)">{{t}}</button></nav><button class="button" :disabled="busy||!catalog" @click="create">创建规则</button><form class="filter-grid" v-if="showForm&&catalog" @submit.prevent="save"><label>名称<input v-model="name" required maxlength="80" /></label><label>来源<select aria-label="来源" v-model="source"><option v-for="s in catalog.creatable_sources" :key="s">{{s}}</option></select></label><label v-if="source==='metrics'">指标<select aria-label="指标" v-model="metric"><option v-for="m in catalog.metrics" :key="m.metric">{{m.metric}}</option></select></label><label>固定选择器<select aria-label="固定选择器" v-model="tuple"><option v-for="(s,i) in selectors" :key="i" :value="i">{{JSON.stringify(s)}}</option></select></label><label>聚合<select aria-label="聚合" v-model="reducer"><option v-for="r in reducers" :key="r">{{r}}</option></select></label><label>运算<select aria-label="运算" v-model="operator"><option v-for="o in catalog.operators" :key="o">{{o}}</option></select></label><label>阈值<input v-model.number="threshold" type="number" step="any" required /></label><label>窗口<select aria-label="窗口" v-model="windowSize"><option v-for="w in catalog.windows" :key="w">{{w}}</option></select></label><label>持续<select aria-label="持续" v-model="forSize"><option v-for="f in durations" :key="f">{{f}}</option></select></label><label>严重度<select aria-label="严重度" v-model="severity"><option v-for="s in catalog.severities" :key="s">{{s}}</option></select></label><button class="button" :disabled="busy">保存规则</button><button class="button" type="button" @click="showForm=false">取消</button></form><p v-if="!busy&&!rules.length">暂无规则</p><article class="panel" v-for="r in rules" :key="r.id" :data-rule-id="r.id"><h3>{{r.name}} · #{{r.id}} / revision {{r.revision}}</h3><p>{{r.source}} · {{r.severity}} · {{r.evaluation.state}} · {{r.evaluation.data_status}}</p><p>{{JSON.stringify(r.selector)}}</p><button class="button" :disabled="busy" @click="edit(r)">编辑</button><button class="button" :disabled="busy" @click="mutate(r,r.enabled?'disable':'enable')">{{r.enabled?'停用':'启用'}}</button><button class="button" :disabled="busy" @click="mutate(r,'delete')">删除</button></article></template><template v-else>
<div class="summary-grid" aria-label="已加载告警摘要"><AdminStat label="Firing" :value="loaded?incidents.filter(row=>row.status==='firing').length:'未知'" note="已加载的触发中告警" icon="alerts" tone="red"/><AdminStat label="Warning" :value="loaded?incidents.filter(row=>row.severity==='warning').length:'未知'" note="已加载的 warning 严重程度" icon="warning" tone="orange"/><AdminStat label="Recovered" :value="loaded?incidents.filter(row=>row.status==='recovered').length:'未知'" note="已加载的已恢复告警" icon="check" tone="green"/><AdminStat label="Closed" :value="loaded?incidents.filter(row=>row.status==='closed').length:'未知'" note="已加载的已关闭告警" icon="stop" tone="purple"/></div>

<p v-if="busy" role="status">正在读取告警…</p><p v-if="!busy&&!visibleIncidents.length">暂无告警记录</p>
<div class="list-detail-layout" :class="{'has-detail':selectedIncident}"><div class="panel incident-list"><header class="panel-heading"><h3>告警列表</h3><nav class="alert-tabs" aria-label="告警视图"><button v-for="t in ['current','history','rules']" :key="t" :disabled="busy" :aria-pressed="tab===t" @click="selectTab(t)">{{t}}</button></nav></header><form class="filter-bar alert-filters" @submit.prevent><label>严重程度<select v-model="severityFilter"><option value="">全部</option><option>warning</option><option>critical</option></select></label><label>生命周期状态<select v-model="statusFilter"><option value="">全部</option><option>firing</option><option>recovered</option><option>closed</option></select></label><label>名称（已加载记录）<input v-model.trim="search"></label></form><div class="table-scroll"><table><thead><tr><th>严重程度</th><th>告警名称</th><th>来源</th><th>状态</th><th>最近触发</th></tr></thead><tbody><tr v-for="r in visibleIncidents" :key="r.id" :class="{'is-selected':selectedId===r.id}"><td><span class="level" :class="`level--${r.severity}`">{{r.severity}}</span></td><td class="message-cell"><button class="row-select" :title="r.name" :aria-pressed="selectedId===r.id" @click="selectIncident(r.id,$event)">{{r.name}}</button></td><td>{{r.source}}</td><td><span class="status-label" :class="`status-label--${r.status}`">{{r.status}}</span><small v-if="r.data_status!=='ok'" class="muted">{{r.data_status}}</small></td><td>{{new Date(r.last_triggered_at).toLocaleTimeString('zh-CN', { hour12:false })}}</td></tr></tbody></table></div></div>
<aside v-if="selectedIncident" ref="detail" class="panel detail-panel" aria-label="告警详情" tabindex="-1" @keydown.esc="closeDetail"><header><div class="detail-heading-copy"><h3>{{selectedIncident.name}}</h3><span class="status-label" :class="`status-label--${selectedIncident.status}`">{{selectedIncident.status}}</span></div><button class="icon-button" aria-label="关闭详情" @click="closeDetail"><AdminIcon name="close" /></button></header><div class="detail-section-label">详情</div><h4>基本信息</h4><dl class="detail-fields"><dt>严重程度</dt><dd><span class="level" :class="`level--${selectedIncident.severity}`">{{selectedIncident.severity}}</span></dd><dt>生命周期状态</dt><dd><span class="status-label" :class="`status-label--${selectedIncident.status}`">{{selectedIncident.status}}</span></dd><dt>数据状态</dt><dd>{{selectedIncident.data_status}}</dd><dt>规则 / 修订</dt><dd>{{selectedIncident.rule_id}} / {{selectedIncident.revision}}</dd><dt>来源</dt><dd>{{selectedIncident.source}}</dd><dt>首次触发</dt><dd>{{new Date(selectedIncident.first_triggered_at).toLocaleString('zh-CN', { hour12:false })}}</dd><dt>最近触发</dt><dd>{{new Date(selectedIncident.last_triggered_at).toLocaleString('zh-CN', { hour12:false })}}</dd><dt>最近值</dt><dd>{{selectedIncident.last_value??'unknown'}}</dd><dt>评估次数</dt><dd>{{selectedIncident.evaluation_count}}</dd><dt>恢复时间</dt><dd>{{selectedIncident.recovered_at?new Date(selectedIncident.recovered_at).toLocaleString('zh-CN', {hour12:false}):'—'}}</dd><dt>关闭时间 / 原因</dt><dd>{{selectedIncident.closed_at?new Date(selectedIncident.closed_at).toLocaleString('zh-CN', {hour12:false}):'—'}} {{selectedIncident.resolution_reason}}</dd></dl><h4>触发对象</h4><pre class="safe-message">{{selectedIncident.object.metric || selectedIncident.source}}</pre><h4>标签（Labels）</h4><dl class="safe-tags"><div v-for="(value,key) in selectedIncident.object.labels" :key="key"><dt>{{key}}</dt><dd>{{value}}</dd></div></dl><p class="panel-footnote">状态来自实际评估记录；不提供静默、手工确认或关联 Trace。</p></aside></div>
</template><button class="button" v-if="next" :disabled="busy" @click="load(true)">更多告警</button></section></template>
