<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { requestValidatedPage } from '../services/http'
import { isAuditEvent, type AuditEvent as Event } from '../services/management'
const rows=ref<Event[]>([]),next=ref<string|null>(null),busy=ref(false),error=ref(false),action=ref(''),resource=ref(''),outcome=ref(''),start=ref(''),end=ref('')
const actions=['bootstrap.declare','user.role.change',...['create','update','enable','disable','delete'].map(v=>'rule.'+v),...['connection-test','install','configuration','start','stop','update'].map(v=>'plugin.'+v),...['trigger','recover','close'].map(v=>'alert.'+v)]
async function load(more=false){if(busy.value)return;busy.value=true;error.value=false;try{const q=new URLSearchParams();if(more&&next.value)q.set('cursor',next.value);else{if(action.value)q.set('action',action.value);if(resource.value)q.set('resource_type',resource.value);if(outcome.value)q.set('outcome',outcome.value);if(start.value)q.set('start',new Date(start.value).toISOString());if(end.value)q.set('end',new Date(end.value).toISOString())}const page=await requestValidatedPage('/admin/audit-events?'+q,isAuditEvent);rows.value=more?[...rows.value,...page.data]:page.data;next.value=page.nextCursor}catch{error.value=true}finally{busy.value=false}}
onMounted(()=>load())
</script>
<template><section><h2>管理审计</h2><form @submit.prevent="load()"><label>操作<select aria-label="操作" v-model="action"><option value="">全部</option><option v-for="a in actions" :key="a">{{a}}</option></select></label><label>资源<select aria-label="资源" v-model="resource"><option value="">全部</option><option v-for="r in ['user','rule','plugin','alert']" :key="r">{{r}}</option></select></label><label>结果<select aria-label="结果" v-model="outcome"><option value="">全部</option><option v-for="o in ['succeeded','failed','unknown']" :key="o">{{o}}</option></select></label><label>开始<input v-model="start" type="datetime-local" /></label><label>结束<input v-model="end" type="datetime-local" /></label><button :disabled="busy">筛选审计</button></form><p>{{Intl.DateTimeFormat().resolvedOptions().timeZone}}</p><p v-if="error" role="alert">审计查询失败</p><p v-if="!busy&&!rows.length">暂无审计记录</p><table><thead><tr><th>时间 / Actor</th><th>操作 / 资源</th><th>阶段 / 结果</th><th>Request ID / Details</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td>{{new Date(r.occurred_at).toLocaleString()}} / {{r.actor_user_id??'system'}}</td><td>{{r.action}} / {{r.resource_type}}:{{r.resource_id}}</td><td>{{r.phase}} / {{r.outcome}}</td><td>{{r.request_id}} / {{JSON.stringify(r.details_json)}}</td></tr></tbody></table><button v-if="next" :disabled="busy" @click="load(true)">更多审计</button></section></template>
