package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"github.com/Ray-ymq/GoPulse/monitor/internal/plugin"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	output := flag.String("output", "", "generated Go file")
	flag.Parse()
	releases := []plugin.Release{}
	seen := map[string]bool{}
	for _, arg := range flag.Args() {
		purpose, path, ok := strings.Cut(arg, "=")
		if !ok {
			panic("invalid release input")
		}
		path, _ = filepath.Abs(path)
		r, err := plugin.InspectBuildRelease(path, purpose)
		if err != nil {
			panic("invalid release input")
		}
		key := r.Manifest.ID + "/" + r.Manifest.Version + "/" + r.Manifest.Arch
		if seen[key] {
			panic("duplicate release")
		}
		seen[key] = true
		releases = append(releases, r)
	}
	data, err := json.Marshal(releases)
	if err != nil {
		panic(err)
	}
	source := "// Code generated by plugin-release-catalog; DO NOT EDIT.\npackage plugin\nconst compiledReleaseJSON = " + strconv.Quote(string(data)) + "\n"
	if *output == "" {
		fmt.Print(source)
		return
	}
	if os.WriteFile(*output, []byte(source), 0644) != nil {
		panic("cannot write catalog")
	}
}
