import { expect, test, type Page } from '@playwright/test'
const admin = process.env.GOPULSE_OBSERVABILITY_ADMIN_USERNAME!
const user = process.env.GOPULSE_OBSERVABILITY_USER_USERNAME!
const password = process.env.GOPULSE_OBSERVABILITY_PASSWORD!
test.use({ timezoneId: 'Asia/Shanghai', viewport: process.env.GOPULSE_VIEWPORT === 'narrow' ? { width: 390, height: 844 } : { width: 1440, height: 900 } })
async function login(page: Page, name: string) {
  await page.getByLabel('用户名').fill(name)
  await page.getByLabel('密码').fill(password)
  await page.getByLabel('密码').press('Enter')
}
test('product edge, keyboard login, roles, logout, recovery and local audit time', async ({ page, context }) => {
  test.setTimeout(120_000)
  await page.goto('/admin/audit')
  await expect(page).toHaveURL(/\/login\?redirect=/)
  await login(page, admin)
  await expect(page).toHaveURL(/\/admin\/audit$/)
  const response = await page.request.get('/admin/audit')
  expect(response.headers()['x-content-type-options']).toBe('nosniff')
  expect(response.headers()['x-frame-options']).toBe('DENY')
  expect(response.headers()['content-security-policy']).toContain("frame-ancestors 'none'")
  expect(response.headers()['cache-control']).toContain('no-store')
  for (const cookie of await context.cookies()) { expect(cookie.httpOnly).toBe(true); expect(cookie.path).toBe('/'); expect(cookie.sameSite).toBe('Lax'); expect(cookie.secure).toBe(false) }
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([])
  expect((await page.request.post('/api/v1/auth/logout', { headers: { Origin: 'https://evil.invalid' } })).status()).toBe(403)
  expect((await page.request.get('/api/v1/users/me')).status()).toBe(200)
  await page.keyboard.press('Tab')
  await page.locator('.gp-skip').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#admin-main')).toBeFocused()
  await page.getByLabel('开始', { exact: true }).fill('2026-09-13T00:00')
  const query = page.waitForRequest(r => r.url().includes('/admin/audit-events?') && r.url().includes('start='))
  await page.getByRole('button', { name: '筛选审计' }).click()
  expect(new URL((await query).url()).searchParams.get('start')).toBe('2026-09-12T16:00:00.000Z')
  await page.getByLabel('开始', { exact: true }).fill('')
  await page.getByRole('button', { name: '筛选审计' }).click()
  await expect(page.locator('time').first()).toBeVisible()
  const time = page.locator('time').first()
  const utc = await time.getAttribute('datetime')
  expect(await time.getAttribute('title')).toBe(utc)
  expect(await time.textContent()).toBe(await page.evaluate(value => new Intl.DateTimeFormat('zh-CN', {year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value!)), utc))
  for (const path of ['metrics','events','logs','plugins','users','alerts']) {
    await page.goto('/admin/'+path)
    await expect(page.locator('#admin-main')).toBeVisible()
    const logout = page.getByRole('button', { name: '退出登录', exact: true })
    await expect(logout).toBeInViewport()
  }
  await page.getByRole('button', { name: '退出登录', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  expect((await page.request.get('/api/v1/users/me')).status()).toBe(401)
  await page.goto('/login?redirect=/api/v1/users/me')
  await login(page, user)
  await expect(page).toHaveURL(/\/posts$/)
  expect((await page.request.get('/api/v1/admin/users/1')).status()).toBe(403)
  await page.goto('/admin/users')
  await expect(page).toHaveURL(/\/posts$/)
  await page.route('**/api/v1/users/me', route => route.fulfill({status:503, contentType:'application/json',body:'{"error":{"code":"internal_error","message":"unavailable"}}'}))
  await page.reload()
  await expect(page).toHaveURL(/\/auth-recovery/)
  await page.unroute('**/api/v1/users/me')
  await page.getByRole('button', {name:'重试认证恢复'}).click()
  await expect(page).toHaveURL(/\/posts$/)
  // End the recovery document before injecting expiry: pending recovery reads
  // must not race a second, independent authentication failure fixture.
  await page.goto('about:blank')
  await context.clearCookies()
  await page.goto('/posts')
  await expect(page).toHaveURL(/\/login/)
})
test('shared event states expose loading, stale failure, empty and retry', async ({ page }) => {
  await page.goto('/login')
  await login(page, admin)
  await expect(page).toHaveURL(/\/admin\/$/)
  await page.goto('/admin/events')
  await expect(page.locator('.record-card').first()).toBeVisible({ timeout: 15_000 })
  await page.route('**/api/v1/observability/events?*', async route => {
    await new Promise(resolve => setTimeout(resolve, 500))
    await route.fulfill({status:503,contentType:'application/json',body:'{"error":{"code":"events_unavailable","message":"unavailable"}}'})
  })
  await page.getByRole('button', {name:'刷新',exact:true}).click()
  await expect(page.locator('[data-state="loading"]')).toBeVisible()
  await expect(page.locator('[data-state="stale"]')).toBeVisible()
  await expect(page.locator('.record-card').first()).toBeVisible()
  await page.reload()
  await expect(page.locator('[data-state="unavailable"]')).toBeVisible()
  await page.unroute('**/api/v1/observability/events?*')
  await page.route('**/api/v1/observability/events?*', route => route.fulfill({status:200,contentType:'application/json',body:'{"data":[],"meta":{"next_cursor":null}}'}))
  await page.getByRole('button', {name:'刷新',exact:true}).click()
  await expect(page.locator('[data-state="empty"]')).toBeVisible()
  await page.unroute('**/api/v1/observability/events?*')
  await page.getByRole('button', {name:'刷新',exact:true}).click()
  await expect(page.locator('.record-card').first()).toBeVisible()
})
