import { expect, test } from '@playwright/test'

test('six available plugins and VictoriaMetrics configuration, lifecycle and query', async ({ page }) => {
  test.skip(!process.env.GOPULSE_P14_ADMIN, 'requires the owned six-source acceptance')
  test.setTimeout(120_000)
  await page.goto('/login')
  await page.getByLabel('用户名').fill(process.env.GOPULSE_P14_ADMIN!)
  await page.getByLabel('密码').fill(process.env.GOPULSE_P14_PASSWORD!)
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page).toHaveURL(/\/admin\/$/)
  await page.goto('/admin/plugins')
  await expect(page.getByRole('button').filter({ hasText: 'GoPulse' })).toHaveCount(6)
  await expect(page.getByRole('button').filter({ hasText: '未交付' })).toHaveCount(0)
  await page.getByRole('button').filter({ hasText: 'GoPulse victoriametrics Exporter' }).click()
  await page.getByLabel('host', { exact: true }).fill('victoriametrics')
  await page.getByLabel('username', { exact: true }).fill(process.env.GOPULSE_VM_USER!)
  await page.getByLabel('password', { exact: true }).fill(process.env.GOPULSE_VM_PASSWORD!)
  await page.getByRole('button', { name: '连接测试', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('连接测试成功')
  await expect(page.getByLabel('password', { exact: true })).toHaveValue('')
  await page.getByLabel('password', { exact: true }).fill(process.env.GOPULSE_VM_PASSWORD!)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '替换配置', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('配置已验证并保存')
  await expect(page.getByLabel('password', { exact: true })).toHaveValue('')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '停止', exact: true }).click()
  await expect(page.locator('.state-pill')).toHaveText('stopped')
  await page.getByRole('button', { name: '启动', exact: true }).click()
  await expect(page.locator('.state-pill')).toHaveText('running')
  await page.getByRole('link', { name: '查询插件指标' }).click()
  await expect(page.locator('.metric-value').first()).toBeVisible()
  await page.locator('form.filter-bar select').first().selectOption('gopulse_victoriametrics_storage_rows_deleted_total')
  await page.getByRole('button', { name: '应用', exact: true }).click()
  await expect(page.locator('.metric-value')).toHaveCount(1)
})
