import { expect, test } from '@playwright/test'

test('Phase 14 Redis schema lifecycle and safe unavailable cards', async ({ page }) => {
  test.skip(!process.env.GOPULSE_P14_ADMIN, 'run through verify-plugin-metrics.sh')
  test.setTimeout(120_000)
  await page.goto('/login')
  await page.getByLabel('用户名').fill(process.env.GOPULSE_P14_ADMIN!)
  await page.getByLabel('密码').fill(process.env.GOPULSE_P14_PASSWORD!)
  await page.getByRole('button', {name:'登录',exact:true}).click()
  await expect(page).toHaveURL(/\/admin\/metrics$/)
  await page.goto('/admin/plugins')
  await page.getByLabel('host', { exact: true }).fill('redis')
  await expect(page.getByRole('heading',{name:'官方 Exporter 插件'})).toBeVisible()
  await expect(page.getByRole('button').filter({hasText:'未交付'})).toHaveCount(5)
  await page.getByLabel('password',{exact:true}).fill(process.env.GOPULSE_P14_SECRET!)
  await page.getByRole('button',{name:'连接测试',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('连接测试成功')
  await expect(page.getByLabel('password',{exact:true})).toHaveValue('')
  await page.getByLabel('password',{exact:true}).fill(process.env.GOPULSE_P14_SECRET!)
  await page.getByRole('button',{name:'安装并启动',exact:true}).click()
  await expect(page.locator('.state-pill')).toHaveText('running')
  await expect(page.getByLabel('password',{exact:true})).toHaveValue('')
  page.once('dialog', dialog=>dialog.accept())
  await page.getByRole('button',{name:'替换配置',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('配置已验证并保存')
  await page.getByLabel('password',{exact:true}).fill('bad-browser-secret-canary')
  await page.getByRole('button',{name:'连接测试',exact:true}).click()
  await expect(page.getByLabel('password',{exact:true})).toHaveValue('')
  expect(await page.content()).not.toContain(process.env.GOPULSE_P14_SECRET!)
  expect(await page.content()).not.toContain('bad-browser-secret-canary')
  await page.getByRole('button').filter({hasText:'GoPulse mysql Exporter'}).click()
  await expect(page.locator('.state-pill')).toHaveCount(0)
  await expect(page.getByText('此类型尚未交付，没有已安装或运行中的实例。')).toBeVisible()
  await page.getByRole('button').filter({hasText:'GoPulse redis Exporter'}).click()
  await page.getByRole('link',{name:'查询 Redis 指标'}).click()
  await expect(page.getByRole('heading',{name:'Redis Metrics'})).toBeVisible()
  const catalog = await page.request.get('/api/v1/observability/metrics/catalog')
  expect(catalog.status()).toBe(200)
  const catalogBody = await catalog.json()
  console.log('metric catalog schema', JSON.stringify(catalogBody))
  const query = await page.request.get('/api/v1/observability/metrics?metric=gopulse_redis_up&range=15m')
  const queryBody = await query.json()
  console.log('metric query status/series', query.status(), queryBody.data?.series?.length)
  console.log('metric page notice', await page.locator('.notice').allTextContents())
  await expect(page.locator('.metric-value').first()).toBeVisible({timeout:30_000})
})
