import { expect, test } from '@playwright/test'

test('empty-volume Redis schema, installation, lifecycle, trusted update and query', async ({ page }) => {
  test.skip(!process.env.GOPULSE_P14_ADMIN, 'requires owned Phase 14 closure')
  test.setTimeout(120_000)
  await page.goto('/login')
  await page.getByLabel('用户名').fill(process.env.GOPULSE_P14_ADMIN!)
  await page.getByLabel('密码').fill(process.env.GOPULSE_P14_PASSWORD!)
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page).toHaveURL(/\/admin\/metrics$/)
  await page.goto('/admin/plugins')
  await page.getByLabel('host', { exact: true }).fill('redis')
  await expect(page.getByRole('button').filter({ hasText: 'GoPulse' })).toHaveCount(6)
  await expect(page.locator('.state-pill')).toHaveCount(0)
  await page.getByLabel('password', { exact: true }).fill(process.env.GOPULSE_P14_SECRET!)
  await page.getByRole('button', { name: '连接测试', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('连接测试成功')
  await expect(page.getByLabel('password', { exact: true })).toHaveValue('')
  await page.getByLabel('password', { exact: true }).fill(process.env.GOPULSE_P14_SECRET!)
  await page.getByRole('button', { name: '安装并启动', exact: true }).click()
  await expect(page.locator('.state-pill')).toHaveText('running')
  await expect(page.getByLabel('password', { exact: true })).toHaveValue('')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '停止', exact: true }).click()
  await expect(page.locator('.state-pill')).toHaveText('stopped')
  await page.getByRole('button', { name: '启动', exact: true }).click()
  await expect(page.locator('.state-pill')).toHaveText('running')
  await page.locator('input[type=file]').setInputFiles('/work/packages/closure-redis.tar.gz')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '确认更新', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('更新请求已完成')
  expect(await page.content()).not.toContain(process.env.GOPULSE_P14_SECRET!)
  await page.getByRole('link', { name: '查询插件指标' }).click()
  await expect(page.locator('.metric-value').first()).toBeVisible({ timeout: 30_000 })
})
